### ISSUE TITLE
Divisions by 0

### ISSUE THREAD

**Issue by LysanderGG** [jobtalle/ccVector#1]
Hi, I just had a look at your project (from stb) and noticed that there are a few possible divisions by 0.

In _CCV_FUNC_MAT_INVERSE if the matrices are not invertible, the determinant will be 0 and therefore 1 / det is not computable.

Also for _CCV_FUNC_MAT_PERSPECTIVE if the user gives unappropriated values, such as angle = 0, aspect = 0 or zNear = zFar, it will lead to other divisions by 0 and therefore a crash.

While giving wrong arguments for _CCV_FUNC_MAT_PERSPECTIVE can be easily avoided by the user, I think it would be better to add asserts.

Just my two cents.

**Comment by jobtalle** [comment]
Thank you for pointing this out, I'll implement assertions soon.
